server:
    host: 127.0.0.1
    port: :8080
    storage_type: postgres
    db_connection_url: postgres://postgres:postgres@postgres:5432/o3_test_task?sslmode=disable
    db_migrations_folder: file://migrations
    