DROP TABLE IF EXISTS public.post CASCADE;
DROP TABLE IF EXISTS public.comment CASCADE;

CREATE TABLE IF NOT EXISTS public.post
(
    id                    BIGINT                                         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id               BIGINT                                         NOT NULL,
    title                 TEXT                                           NOT NULL CHECK (title <> ''),
    content               TEXT                                           NOT NULL CHECK (content <> ''),
    created_time          TIMESTAMP DEFAULT NOW()                        NOT NULL,
    are_comments_disabled BOOLEAN   DEFAULT FALSE    
);

CREATE TABLE IF NOT EXISTS public.comment
(
    id                    BIGINT                                         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id               BIGINT                                         NOT NULL REFERENCES public.post (id) ON DELETE CASCADE,
    parent_comment_id     BIGINT                                         NOT NULL REFERENCES public.comment (id) ON DELETE CASCADE,
    user_id               BIGINT                                         NOT NULL,
    content               TEXT                                           NOT NULL CHECK (content <> '')
        CONSTRAINT max_len_content CHECK (LENGTH(content) <= 2000),
    created_time          TIMESTAMP DEFAULT NOW()                        NOT NULL
);
